"use strict";
// automatically generated by the FlatBuffers compiler, do not modify
exports.__esModule = true;
exports.CallOptions = void 0;
var flatbuffers = require("flatbuffers");
var CallOptions = /** @class */ (function () {
    function CallOptions() {
        this.bb = null;
        this.bb_pos = 0;
    }
    CallOptions.prototype.__init = function (i, bb) {
        this.bb_pos = i;
        this.bb = bb;
        return this;
    };
    CallOptions.getRootAsCallOptions = function (bb, obj) {
        return (obj || new CallOptions()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
    };
    CallOptions.getSizePrefixedRootAsCallOptions = function (bb, obj) {
        bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
        return (obj || new CallOptions()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
    };
    CallOptions.prototype.subgraph = function () {
        var offset = this.bb.__offset(this.bb_pos, 4);
        return offset ? this.bb.readUint32(this.bb_pos + offset) : 0;
    };
    CallOptions.startCallOptions = function (builder) {
        builder.startObject(1);
    };
    CallOptions.addSubgraph = function (builder, subgraph) {
        builder.addFieldInt32(0, subgraph, 0);
    };
    CallOptions.endCallOptions = function (builder) {
        var offset = builder.endObject();
        return offset;
    };
    CallOptions.createCallOptions = function (builder, subgraph) {
        CallOptions.startCallOptions(builder);
        CallOptions.addSubgraph(builder, subgraph);
        return CallOptions.endCallOptions(builder);
    };
    return CallOptions;
}());
exports.CallOptions = CallOptions;
