"use strict";
// automatically generated by the FlatBuffers compiler, do not modify
exports.__esModule = true;
exports.FillOptions = void 0;
var flatbuffers = require("flatbuffers");
var FillOptions = /** @class */ (function () {
    function FillOptions() {
        this.bb = null;
        this.bb_pos = 0;
    }
    FillOptions.prototype.__init = function (i, bb) {
        this.bb_pos = i;
        this.bb = bb;
        return this;
    };
    FillOptions.getRootAsFillOptions = function (bb, obj) {
        return (obj || new FillOptions()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
    };
    FillOptions.getSizePrefixedRootAsFillOptions = function (bb, obj) {
        bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
        return (obj || new FillOptions()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
    };
    FillOptions.startFillOptions = function (builder) {
        builder.startObject(0);
    };
    FillOptions.endFillOptions = function (builder) {
        var offset = builder.endObject();
        return offset;
    };
    FillOptions.createFillOptions = function (builder) {
        FillOptions.startFillOptions(builder);
        return FillOptions.endFillOptions(builder);
    };
    return FillOptions;
}());
exports.FillOptions = FillOptions;
