"use strict";
// automatically generated by the FlatBuffers compiler, do not modify
exports.__esModule = true;
exports.IfOptions = void 0;
var flatbuffers = require("flatbuffers");
var IfOptions = /** @class */ (function () {
    function IfOptions() {
        this.bb = null;
        this.bb_pos = 0;
    }
    IfOptions.prototype.__init = function (i, bb) {
        this.bb_pos = i;
        this.bb = bb;
        return this;
    };
    IfOptions.getRootAsIfOptions = function (bb, obj) {
        return (obj || new IfOptions()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
    };
    IfOptions.getSizePrefixedRootAsIfOptions = function (bb, obj) {
        bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
        return (obj || new IfOptions()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
    };
    IfOptions.prototype.thenSubgraphIndex = function () {
        var offset = this.bb.__offset(this.bb_pos, 4);
        return offset ? this.bb.readInt32(this.bb_pos + offset) : 0;
    };
    IfOptions.prototype.elseSubgraphIndex = function () {
        var offset = this.bb.__offset(this.bb_pos, 6);
        return offset ? this.bb.readInt32(this.bb_pos + offset) : 0;
    };
    IfOptions.startIfOptions = function (builder) {
        builder.startObject(2);
    };
    IfOptions.addThenSubgraphIndex = function (builder, thenSubgraphIndex) {
        builder.addFieldInt32(0, thenSubgraphIndex, 0);
    };
    IfOptions.addElseSubgraphIndex = function (builder, elseSubgraphIndex) {
        builder.addFieldInt32(1, elseSubgraphIndex, 0);
    };
    IfOptions.endIfOptions = function (builder) {
        var offset = builder.endObject();
        return offset;
    };
    IfOptions.createIfOptions = function (builder, thenSubgraphIndex, elseSubgraphIndex) {
        IfOptions.startIfOptions(builder);
        IfOptions.addThenSubgraphIndex(builder, thenSubgraphIndex);
        IfOptions.addElseSubgraphIndex(builder, elseSubgraphIndex);
        return IfOptions.endIfOptions(builder);
    };
    return IfOptions;
}());
exports.IfOptions = IfOptions;
