"use strict";
// automatically generated by the FlatBuffers compiler, do not modify
exports.__esModule = true;
exports.Metadata = void 0;
var flatbuffers = require("flatbuffers");
var Metadata = /** @class */ (function () {
    function Metadata() {
        this.bb = null;
        this.bb_pos = 0;
    }
    Metadata.prototype.__init = function (i, bb) {
        this.bb_pos = i;
        this.bb = bb;
        return this;
    };
    Metadata.getRootAsMetadata = function (bb, obj) {
        return (obj || new Metadata()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
    };
    Metadata.getSizePrefixedRootAsMetadata = function (bb, obj) {
        bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
        return (obj || new Metadata()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
    };
    Metadata.prototype.name = function (optionalEncoding) {
        var offset = this.bb.__offset(this.bb_pos, 4);
        return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
    };
    Metadata.prototype.buffer = function () {
        var offset = this.bb.__offset(this.bb_pos, 6);
        return offset ? this.bb.readUint32(this.bb_pos + offset) : 0;
    };
    Metadata.startMetadata = function (builder) {
        builder.startObject(2);
    };
    Metadata.addName = function (builder, nameOffset) {
        builder.addFieldOffset(0, nameOffset, 0);
    };
    Metadata.addBuffer = function (builder, buffer) {
        builder.addFieldInt32(1, buffer, 0);
    };
    Metadata.endMetadata = function (builder) {
        var offset = builder.endObject();
        return offset;
    };
    Metadata.createMetadata = function (builder, nameOffset, buffer) {
        Metadata.startMetadata(builder);
        Metadata.addName(builder, nameOffset);
        Metadata.addBuffer(builder, buffer);
        return Metadata.endMetadata(builder);
    };
    return Metadata;
}());
exports.Metadata = Metadata;
