"use strict";
// automatically generated by the FlatBuffers compiler, do not modify
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    Object.defineProperty(o, k2, { enumerable: true, get: function() { return m[k]; } });
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
var __setModuleDefault = (this && this.__setModuleDefault) || (Object.create ? (function(o, v) {
    Object.defineProperty(o, "default", { enumerable: true, value: v });
}) : function(o, v) {
    o["default"] = v;
});
var __importStar = (this && this.__importStar) || function (mod) {
    if (mod && mod.__esModule) return mod;
    var result = {};
    if (mod != null) for (var k in mod) if (k !== "default" && Object.prototype.hasOwnProperty.call(mod, k)) __createBinding(result, mod, k);
    __setModuleDefault(result, mod);
    return result;
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.Metadata = void 0;
var flatbuffers = __importStar(require("flatbuffers"));
var Metadata = /** @class */ (function () {
    function Metadata() {
        this.bb = null;
        this.bb_pos = 0;
    }
    Metadata.prototype.__init = function (i, bb) {
        this.bb_pos = i;
        this.bb = bb;
        return this;
    };
    Metadata.getRootAsMetadata = function (bb, obj) {
        return (obj || new Metadata()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
    };
    Metadata.getSizePrefixedRootAsMetadata = function (bb, obj) {
        bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
        return (obj || new Metadata()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
    };
    Metadata.prototype.name = function (optionalEncoding) {
        var offset = this.bb.__offset(this.bb_pos, 4);
        return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
    };
    Metadata.prototype.buffer = function () {
        var offset = this.bb.__offset(this.bb_pos, 6);
        return offset ? this.bb.readUint32(this.bb_pos + offset) : 0;
    };
    Metadata.startMetadata = function (builder) {
        builder.startObject(2);
    };
    Metadata.addName = function (builder, nameOffset) {
        builder.addFieldOffset(0, nameOffset, 0);
    };
    Metadata.addBuffer = function (builder, buffer) {
        builder.addFieldInt32(1, buffer, 0);
    };
    Metadata.endMetadata = function (builder) {
        var offset = builder.endObject();
        return offset;
    };
    Metadata.createMetadata = function (builder, nameOffset, buffer) {
        Metadata.startMetadata(builder);
        Metadata.addName(builder, nameOffset);
        Metadata.addBuffer(builder, buffer);
        return Metadata.endMetadata(builder);
    };
    return Metadata;
}());
exports.Metadata = Metadata;
