"use strict";
// automatically generated by the FlatBuffers compiler, do not modify
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    Object.defineProperty(o, k2, { enumerable: true, get: function() { return m[k]; } });
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
var __setModuleDefault = (this && this.__setModuleDefault) || (Object.create ? (function(o, v) {
    Object.defineProperty(o, "default", { enumerable: true, value: v });
}) : function(o, v) {
    o["default"] = v;
});
var __importStar = (this && this.__importStar) || function (mod) {
    if (mod && mod.__esModule) return mod;
    var result = {};
    if (mod != null) for (var k in mod) if (k !== "default" && Object.prototype.hasOwnProperty.call(mod, k)) __createBinding(result, mod, k);
    __setModuleDefault(result, mod);
    return result;
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.MulOptions = void 0;
var flatbuffers = __importStar(require("flatbuffers"));
var activation_function_type_1 = require("../circle/activation-function-type");
var MulOptions = /** @class */ (function () {
    function MulOptions() {
        this.bb = null;
        this.bb_pos = 0;
    }
    MulOptions.prototype.__init = function (i, bb) {
        this.bb_pos = i;
        this.bb = bb;
        return this;
    };
    MulOptions.getRootAsMulOptions = function (bb, obj) {
        return (obj || new MulOptions()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
    };
    MulOptions.getSizePrefixedRootAsMulOptions = function (bb, obj) {
        bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
        return (obj || new MulOptions()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
    };
    MulOptions.prototype.fusedActivationFunction = function () {
        var offset = this.bb.__offset(this.bb_pos, 4);
        return offset ? this.bb.readInt8(this.bb_pos + offset) : activation_function_type_1.ActivationFunctionType.NONE;
    };
    MulOptions.startMulOptions = function (builder) {
        builder.startObject(1);
    };
    MulOptions.addFusedActivationFunction = function (builder, fusedActivationFunction) {
        builder.addFieldInt8(0, fusedActivationFunction, activation_function_type_1.ActivationFunctionType.NONE);
    };
    MulOptions.endMulOptions = function (builder) {
        var offset = builder.endObject();
        return offset;
    };
    MulOptions.createMulOptions = function (builder, fusedActivationFunction) {
        MulOptions.startMulOptions(builder);
        MulOptions.addFusedActivationFunction(builder, fusedActivationFunction);
        return MulOptions.endMulOptions(builder);
    };
    return MulOptions;
}());
exports.MulOptions = MulOptions;
