"use strict";
// automatically generated by the FlatBuffers compiler, do not modify
exports.__esModule = true;
exports.MulOptions = void 0;
var flatbuffers = require("flatbuffers");
var activation_function_type_1 = require("../circle/activation-function-type");
var MulOptions = /** @class */ (function () {
    function MulOptions() {
        this.bb = null;
        this.bb_pos = 0;
    }
    MulOptions.prototype.__init = function (i, bb) {
        this.bb_pos = i;
        this.bb = bb;
        return this;
    };
    MulOptions.getRootAsMulOptions = function (bb, obj) {
        return (obj || new MulOptions()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
    };
    MulOptions.getSizePrefixedRootAsMulOptions = function (bb, obj) {
        bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
        return (obj || new MulOptions()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
    };
    MulOptions.prototype.fusedActivationFunction = function () {
        var offset = this.bb.__offset(this.bb_pos, 4);
        return offset ? this.bb.readInt8(this.bb_pos + offset) : activation_function_type_1.ActivationFunctionType.NONE;
    };
    MulOptions.startMulOptions = function (builder) {
        builder.startObject(1);
    };
    MulOptions.addFusedActivationFunction = function (builder, fusedActivationFunction) {
        builder.addFieldInt8(0, fusedActivationFunction, activation_function_type_1.ActivationFunctionType.NONE);
    };
    MulOptions.endMulOptions = function (builder) {
        var offset = builder.endObject();
        return offset;
    };
    MulOptions.createMulOptions = function (builder, fusedActivationFunction) {
        MulOptions.startMulOptions(builder);
        MulOptions.addFusedActivationFunction(builder, fusedActivationFunction);
        return MulOptions.endMulOptions(builder);
    };
    return MulOptions;
}());
exports.MulOptions = MulOptions;
