"use strict";
// automatically generated by the FlatBuffers compiler, do not modify
exports.__esModule = true;
exports.PackOptions = void 0;
var flatbuffers = require("flatbuffers");
var PackOptions = /** @class */ (function () {
    function PackOptions() {
        this.bb = null;
        this.bb_pos = 0;
    }
    PackOptions.prototype.__init = function (i, bb) {
        this.bb_pos = i;
        this.bb = bb;
        return this;
    };
    PackOptions.getRootAsPackOptions = function (bb, obj) {
        return (obj || new PackOptions()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
    };
    PackOptions.getSizePrefixedRootAsPackOptions = function (bb, obj) {
        bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
        return (obj || new PackOptions()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
    };
    PackOptions.prototype.valuesCount = function () {
        var offset = this.bb.__offset(this.bb_pos, 4);
        return offset ? this.bb.readInt32(this.bb_pos + offset) : 0;
    };
    PackOptions.prototype.axis = function () {
        var offset = this.bb.__offset(this.bb_pos, 6);
        return offset ? this.bb.readInt32(this.bb_pos + offset) : 0;
    };
    PackOptions.startPackOptions = function (builder) {
        builder.startObject(2);
    };
    PackOptions.addValuesCount = function (builder, valuesCount) {
        builder.addFieldInt32(0, valuesCount, 0);
    };
    PackOptions.addAxis = function (builder, axis) {
        builder.addFieldInt32(1, axis, 0);
    };
    PackOptions.endPackOptions = function (builder) {
        var offset = builder.endObject();
        return offset;
    };
    PackOptions.createPackOptions = function (builder, valuesCount, axis) {
        PackOptions.startPackOptions(builder);
        PackOptions.addValuesCount(builder, valuesCount);
        PackOptions.addAxis(builder, axis);
        return PackOptions.endPackOptions(builder);
    };
    return PackOptions;
}());
exports.PackOptions = PackOptions;
