"use strict";
// automatically generated by the FlatBuffers compiler, do not modify
exports.__esModule = true;
exports.PadOptions = void 0;
var flatbuffers = require("flatbuffers");
var PadOptions = /** @class */ (function () {
    function PadOptions() {
        this.bb = null;
        this.bb_pos = 0;
    }
    PadOptions.prototype.__init = function (i, bb) {
        this.bb_pos = i;
        this.bb = bb;
        return this;
    };
    PadOptions.getRootAsPadOptions = function (bb, obj) {
        return (obj || new PadOptions()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
    };
    PadOptions.getSizePrefixedRootAsPadOptions = function (bb, obj) {
        bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
        return (obj || new PadOptions()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
    };
    PadOptions.startPadOptions = function (builder) {
        builder.startObject(0);
    };
    PadOptions.endPadOptions = function (builder) {
        var offset = builder.endObject();
        return offset;
    };
    PadOptions.createPadOptions = function (builder) {
        PadOptions.startPadOptions(builder);
        return PadOptions.endPadOptions(builder);
    };
    return PadOptions;
}());
exports.PadOptions = PadOptions;
