"use strict";
// automatically generated by the FlatBuffers compiler, do not modify
exports.__esModule = true;
exports.Padding = void 0;
var Padding;
(function (Padding) {
    Padding[Padding["SAME"] = 0] = "SAME";
    Padding[Padding["VALID"] = 1] = "VALID";
})(Padding = exports.Padding || (exports.Padding = {}));
