"use strict";
// automatically generated by the FlatBuffers compiler, do not modify
exports.__esModule = true;
exports.RangeOptions = void 0;
var flatbuffers = require("flatbuffers");
var RangeOptions = /** @class */ (function () {
    function RangeOptions() {
        this.bb = null;
        this.bb_pos = 0;
    }
    RangeOptions.prototype.__init = function (i, bb) {
        this.bb_pos = i;
        this.bb = bb;
        return this;
    };
    RangeOptions.getRootAsRangeOptions = function (bb, obj) {
        return (obj || new RangeOptions()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
    };
    RangeOptions.getSizePrefixedRootAsRangeOptions = function (bb, obj) {
        bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
        return (obj || new RangeOptions()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
    };
    RangeOptions.startRangeOptions = function (builder) {
        builder.startObject(0);
    };
    RangeOptions.endRangeOptions = function (builder) {
        var offset = builder.endObject();
        return offset;
    };
    RangeOptions.createRangeOptions = function (builder) {
        RangeOptions.startRangeOptions(builder);
        return RangeOptions.endRangeOptions(builder);
    };
    return RangeOptions;
}());
exports.RangeOptions = RangeOptions;
