"use strict";
// automatically generated by the FlatBuffers compiler, do not modify
exports.__esModule = true;
exports.SelectOptions = void 0;
var flatbuffers = require("flatbuffers");
var SelectOptions = /** @class */ (function () {
    function SelectOptions() {
        this.bb = null;
        this.bb_pos = 0;
    }
    SelectOptions.prototype.__init = function (i, bb) {
        this.bb_pos = i;
        this.bb = bb;
        return this;
    };
    SelectOptions.getRootAsSelectOptions = function (bb, obj) {
        return (obj || new SelectOptions()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
    };
    SelectOptions.getSizePrefixedRootAsSelectOptions = function (bb, obj) {
        bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
        return (obj || new SelectOptions()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
    };
    SelectOptions.startSelectOptions = function (builder) {
        builder.startObject(0);
    };
    SelectOptions.endSelectOptions = function (builder) {
        var offset = builder.endObject();
        return offset;
    };
    SelectOptions.createSelectOptions = function (builder) {
        SelectOptions.startSelectOptions(builder);
        return SelectOptions.endSelectOptions(builder);
    };
    return SelectOptions;
}());
exports.SelectOptions = SelectOptions;
