"use strict";
// automatically generated by the FlatBuffers compiler, do not modify
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    Object.defineProperty(o, k2, { enumerable: true, get: function() { return m[k]; } });
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
var __setModuleDefault = (this && this.__setModuleDefault) || (Object.create ? (function(o, v) {
    Object.defineProperty(o, "default", { enumerable: true, value: v });
}) : function(o, v) {
    o["default"] = v;
});
var __importStar = (this && this.__importStar) || function (mod) {
    if (mod && mod.__esModule) return mod;
    var result = {};
    if (mod != null) for (var k in mod) if (k !== "default" && Object.prototype.hasOwnProperty.call(mod, k)) __createBinding(result, mod, k);
    __setModuleDefault(result, mod);
    return result;
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.ShapeOptions = void 0;
var flatbuffers = __importStar(require("flatbuffers"));
var tensor_type_1 = require("../circle/tensor-type");
var ShapeOptions = /** @class */ (function () {
    function ShapeOptions() {
        this.bb = null;
        this.bb_pos = 0;
    }
    ShapeOptions.prototype.__init = function (i, bb) {
        this.bb_pos = i;
        this.bb = bb;
        return this;
    };
    ShapeOptions.getRootAsShapeOptions = function (bb, obj) {
        return (obj || new ShapeOptions()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
    };
    ShapeOptions.getSizePrefixedRootAsShapeOptions = function (bb, obj) {
        bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
        return (obj || new ShapeOptions()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
    };
    ShapeOptions.prototype.outType = function () {
        var offset = this.bb.__offset(this.bb_pos, 4);
        return offset ? this.bb.readInt8(this.bb_pos + offset) : tensor_type_1.TensorType.FLOAT32;
    };
    ShapeOptions.startShapeOptions = function (builder) {
        builder.startObject(1);
    };
    ShapeOptions.addOutType = function (builder, outType) {
        builder.addFieldInt8(0, outType, tensor_type_1.TensorType.FLOAT32);
    };
    ShapeOptions.endShapeOptions = function (builder) {
        var offset = builder.endObject();
        return offset;
    };
    ShapeOptions.createShapeOptions = function (builder, outType) {
        ShapeOptions.startShapeOptions(builder);
        ShapeOptions.addOutType(builder, outType);
        return ShapeOptions.endShapeOptions(builder);
    };
    return ShapeOptions;
}());
exports.ShapeOptions = ShapeOptions;
