"use strict";
// automatically generated by the FlatBuffers compiler, do not modify
exports.__esModule = true;
exports.SliceOptions = void 0;
var flatbuffers = require("flatbuffers");
var SliceOptions = /** @class */ (function () {
    function SliceOptions() {
        this.bb = null;
        this.bb_pos = 0;
    }
    SliceOptions.prototype.__init = function (i, bb) {
        this.bb_pos = i;
        this.bb = bb;
        return this;
    };
    SliceOptions.getRootAsSliceOptions = function (bb, obj) {
        return (obj || new SliceOptions()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
    };
    SliceOptions.getSizePrefixedRootAsSliceOptions = function (bb, obj) {
        bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
        return (obj || new SliceOptions()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
    };
    SliceOptions.startSliceOptions = function (builder) {
        builder.startObject(0);
    };
    SliceOptions.endSliceOptions = function (builder) {
        var offset = builder.endObject();
        return offset;
    };
    SliceOptions.createSliceOptions = function (builder) {
        SliceOptions.startSliceOptions(builder);
        return SliceOptions.endSliceOptions(builder);
    };
    return SliceOptions;
}());
exports.SliceOptions = SliceOptions;
