"use strict";
// automatically generated by the FlatBuffers compiler, do not modify
exports.__esModule = true;
exports.SquareOptions = void 0;
var flatbuffers = require("flatbuffers");
var SquareOptions = /** @class */ (function () {
    function SquareOptions() {
        this.bb = null;
        this.bb_pos = 0;
    }
    SquareOptions.prototype.__init = function (i, bb) {
        this.bb_pos = i;
        this.bb = bb;
        return this;
    };
    SquareOptions.getRootAsSquareOptions = function (bb, obj) {
        return (obj || new SquareOptions()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
    };
    SquareOptions.getSizePrefixedRootAsSquareOptions = function (bb, obj) {
        bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
        return (obj || new SquareOptions()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
    };
    SquareOptions.startSquareOptions = function (builder) {
        builder.startObject(0);
    };
    SquareOptions.endSquareOptions = function (builder) {
        var offset = builder.endObject();
        return offset;
    };
    SquareOptions.createSquareOptions = function (builder) {
        SquareOptions.startSquareOptions(builder);
        return SquareOptions.endSquareOptions(builder);
    };
    return SquareOptions;
}());
exports.SquareOptions = SquareOptions;
