"use strict";
// automatically generated by the FlatBuffers compiler, do not modify
Object.defineProperty(exports, "__esModule", { value: true });
exports.TensorType = void 0;
var TensorType;
(function (TensorType) {
    TensorType[TensorType["FLOAT32"] = 0] = "FLOAT32";
    TensorType[TensorType["FLOAT16"] = 1] = "FLOAT16";
    TensorType[TensorType["INT32"] = 2] = "INT32";
    TensorType[TensorType["UINT8"] = 3] = "UINT8";
    TensorType[TensorType["INT64"] = 4] = "INT64";
    TensorType[TensorType["STRING"] = 5] = "STRING";
    TensorType[TensorType["BOOL"] = 6] = "BOOL";
    TensorType[TensorType["INT16"] = 7] = "INT16";
    TensorType[TensorType["COMPLEX64"] = 8] = "COMPLEX64";
    TensorType[TensorType["INT8"] = 9] = "INT8";
    TensorType[TensorType["FLOAT64"] = 10] = "FLOAT64";
})(TensorType = exports.TensorType || (exports.TensorType = {}));
