"use strict";
// automatically generated by the FlatBuffers compiler, do not modify
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    Object.defineProperty(o, k2, { enumerable: true, get: function() { return m[k]; } });
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
var __setModuleDefault = (this && this.__setModuleDefault) || (Object.create ? (function(o, v) {
    Object.defineProperty(o, "default", { enumerable: true, value: v });
}) : function(o, v) {
    o["default"] = v;
});
var __importStar = (this && this.__importStar) || function (mod) {
    if (mod && mod.__esModule) return mod;
    var result = {};
    if (mod != null) for (var k in mod) if (k !== "default" && Object.prototype.hasOwnProperty.call(mod, k)) __createBinding(result, mod, k);
    __setModuleDefault(result, mod);
    return result;
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.Uint16Vector = void 0;
var flatbuffers = __importStar(require("flatbuffers"));
var Uint16Vector = /** @class */ (function () {
    function Uint16Vector() {
        this.bb = null;
        this.bb_pos = 0;
    }
    Uint16Vector.prototype.__init = function (i, bb) {
        this.bb_pos = i;
        this.bb = bb;
        return this;
    };
    Uint16Vector.getRootAsUint16Vector = function (bb, obj) {
        return (obj || new Uint16Vector()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
    };
    Uint16Vector.getSizePrefixedRootAsUint16Vector = function (bb, obj) {
        bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
        return (obj || new Uint16Vector()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
    };
    Uint16Vector.prototype.values = function (index) {
        var offset = this.bb.__offset(this.bb_pos, 4);
        return offset ? this.bb.readUint16(this.bb.__vector(this.bb_pos + offset) + index * 2) : 0;
    };
    Uint16Vector.prototype.valuesLength = function () {
        var offset = this.bb.__offset(this.bb_pos, 4);
        return offset ? this.bb.__vector_len(this.bb_pos + offset) : 0;
    };
    Uint16Vector.prototype.valuesArray = function () {
        var offset = this.bb.__offset(this.bb_pos, 4);
        return offset ? new Uint16Array(this.bb.bytes().buffer, this.bb.bytes().byteOffset + this.bb.__vector(this.bb_pos + offset), this.bb.__vector_len(this.bb_pos + offset)) : null;
    };
    Uint16Vector.startUint16Vector = function (builder) {
        builder.startObject(1);
    };
    Uint16Vector.addValues = function (builder, valuesOffset) {
        builder.addFieldOffset(0, valuesOffset, 0);
    };
    Uint16Vector.createValuesVector = function (builder, data) {
        builder.startVector(2, data.length, 2);
        for (var i = data.length - 1; i >= 0; i--) {
            builder.addInt16(data[i]);
        }
        return builder.endVector();
    };
    Uint16Vector.startValuesVector = function (builder, numElems) {
        builder.startVector(2, numElems, 2);
    };
    Uint16Vector.endUint16Vector = function (builder) {
        var offset = builder.endObject();
        return offset;
    };
    Uint16Vector.createUint16Vector = function (builder, valuesOffset) {
        Uint16Vector.startUint16Vector(builder);
        Uint16Vector.addValues(builder, valuesOffset);
        return Uint16Vector.endUint16Vector(builder);
    };
    return Uint16Vector;
}());
exports.Uint16Vector = Uint16Vector;
