"use strict";
// automatically generated by the FlatBuffers compiler, do not modify
exports.__esModule = true;
exports.AbsOptions = void 0;
var flatbuffers = require("flatbuffers");
var AbsOptions = /** @class */ (function () {
    function AbsOptions() {
        this.bb = null;
        this.bb_pos = 0;
    }
    AbsOptions.prototype.__init = function (i, bb) {
        this.bb_pos = i;
        this.bb = bb;
        return this;
    };
    AbsOptions.getRootAsAbsOptions = function (bb, obj) {
        return (obj || new AbsOptions()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
    };
    AbsOptions.getSizePrefixedRootAsAbsOptions = function (bb, obj) {
        bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
        return (obj || new AbsOptions()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
    };
    AbsOptions.startAbsOptions = function (builder) {
        builder.startObject(0);
    };
    AbsOptions.endAbsOptions = function (builder) {
        var offset = builder.endObject();
        return offset;
    };
    AbsOptions.createAbsOptions = function (builder) {
        AbsOptions.startAbsOptions(builder);
        return AbsOptions.endAbsOptions(builder);
    };
    return AbsOptions;
}());
exports.AbsOptions = AbsOptions;
