"use strict";
// automatically generated by the FlatBuffers compiler, do not modify
exports.__esModule = true;
exports.AddOptions = void 0;
var flatbuffers = require("flatbuffers");
var activation_function_type_1 = require("../circle/activation-function-type");
var AddOptions = /** @class */ (function () {
    function AddOptions() {
        this.bb = null;
        this.bb_pos = 0;
    }
    AddOptions.prototype.__init = function (i, bb) {
        this.bb_pos = i;
        this.bb = bb;
        return this;
    };
    AddOptions.getRootAsAddOptions = function (bb, obj) {
        return (obj || new AddOptions()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
    };
    AddOptions.getSizePrefixedRootAsAddOptions = function (bb, obj) {
        bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
        return (obj || new AddOptions()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
    };
    AddOptions.prototype.fusedActivationFunction = function () {
        var offset = this.bb.__offset(this.bb_pos, 4);
        return offset ? this.bb.readInt8(this.bb_pos + offset) : activation_function_type_1.ActivationFunctionType.NONE;
    };
    AddOptions.startAddOptions = function (builder) {
        builder.startObject(1);
    };
    AddOptions.addFusedActivationFunction = function (builder, fusedActivationFunction) {
        builder.addFieldInt8(0, fusedActivationFunction, activation_function_type_1.ActivationFunctionType.NONE);
    };
    AddOptions.endAddOptions = function (builder) {
        var offset = builder.endObject();
        return offset;
    };
    AddOptions.createAddOptions = function (builder, fusedActivationFunction) {
        AddOptions.startAddOptions(builder);
        AddOptions.addFusedActivationFunction(builder, fusedActivationFunction);
        return AddOptions.endAddOptions(builder);
    };
    return AddOptions;
}());
exports.AddOptions = AddOptions;
