"use strict";
// automatically generated by the FlatBuffers compiler, do not modify
exports.__esModule = true;
exports.Buffer = void 0;
var flatbuffers = require("flatbuffers");
var Buffer = /** @class */ (function () {
    function Buffer() {
        this.bb = null;
        this.bb_pos = 0;
    }
    Buffer.prototype.__init = function (i, bb) {
        this.bb_pos = i;
        this.bb = bb;
        return this;
    };
    Buffer.getRootAsBuffer = function (bb, obj) {
        return (obj || new Buffer()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
    };
    Buffer.getSizePrefixedRootAsBuffer = function (bb, obj) {
        bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
        return (obj || new Buffer()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
    };
    Buffer.prototype.data = function (index) {
        var offset = this.bb.__offset(this.bb_pos, 4);
        return offset ? this.bb.readUint8(this.bb.__vector(this.bb_pos + offset) + index) : 0;
    };
    Buffer.prototype.dataLength = function () {
        var offset = this.bb.__offset(this.bb_pos, 4);
        return offset ? this.bb.__vector_len(this.bb_pos + offset) : 0;
    };
    Buffer.prototype.dataArray = function () {
        var offset = this.bb.__offset(this.bb_pos, 4);
        return offset ? new Uint8Array(this.bb.bytes().buffer, this.bb.bytes().byteOffset + this.bb.__vector(this.bb_pos + offset), this.bb.__vector_len(this.bb_pos + offset)) : null;
    };
    Buffer.startBuffer = function (builder) {
        builder.startObject(1);
    };
    Buffer.addData = function (builder, dataOffset) {
        builder.addFieldOffset(0, dataOffset, 0);
    };
    Buffer.createDataVector = function (builder, data) {
        builder.startVector(1, data.length, 1);
        for (var i = data.length - 1; i >= 0; i--) {
            builder.addInt8(data[i]);
        }
        return builder.endVector();
    };
    Buffer.startDataVector = function (builder, numElems) {
        builder.startVector(1, numElems, 1);
    };
    Buffer.endBuffer = function (builder) {
        var offset = builder.endObject();
        return offset;
    };
    Buffer.createBuffer = function (builder, dataOffset) {
        Buffer.startBuffer(builder);
        Buffer.addData(builder, dataOffset);
        return Buffer.endBuffer(builder);
    };
    return Buffer;
}());
exports.Buffer = Buffer;
