"use strict";
// automatically generated by the FlatBuffers compiler, do not modify
exports.__esModule = true;
exports.CosOptions = void 0;
var flatbuffers = require("flatbuffers");
var CosOptions = /** @class */ (function () {
    function CosOptions() {
        this.bb = null;
        this.bb_pos = 0;
    }
    CosOptions.prototype.__init = function (i, bb) {
        this.bb_pos = i;
        this.bb = bb;
        return this;
    };
    CosOptions.getRootAsCosOptions = function (bb, obj) {
        return (obj || new CosOptions()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
    };
    CosOptions.getSizePrefixedRootAsCosOptions = function (bb, obj) {
        bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
        return (obj || new CosOptions()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
    };
    CosOptions.startCosOptions = function (builder) {
        builder.startObject(0);
    };
    CosOptions.endCosOptions = function (builder) {
        var offset = builder.endObject();
        return offset;
    };
    CosOptions.createCosOptions = function (builder) {
        CosOptions.startCosOptions(builder);
        return CosOptions.endCosOptions(builder);
    };
    return CosOptions;
}());
exports.CosOptions = CosOptions;
