"use strict";
// automatically generated by the FlatBuffers compiler, do not modify
exports.__esModule = true;
exports.DensifyOptions = void 0;
var flatbuffers = require("flatbuffers");
var DensifyOptions = /** @class */ (function () {
    function DensifyOptions() {
        this.bb = null;
        this.bb_pos = 0;
    }
    DensifyOptions.prototype.__init = function (i, bb) {
        this.bb_pos = i;
        this.bb = bb;
        return this;
    };
    DensifyOptions.getRootAsDensifyOptions = function (bb, obj) {
        return (obj || new DensifyOptions()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
    };
    DensifyOptions.getSizePrefixedRootAsDensifyOptions = function (bb, obj) {
        bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
        return (obj || new DensifyOptions()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
    };
    DensifyOptions.startDensifyOptions = function (builder) {
        builder.startObject(0);
    };
    DensifyOptions.endDensifyOptions = function (builder) {
        var offset = builder.endObject();
        return offset;
    };
    DensifyOptions.createDensifyOptions = function (builder) {
        DensifyOptions.startDensifyOptions(builder);
        return DensifyOptions.endDensifyOptions(builder);
    };
    return DensifyOptions;
}());
exports.DensifyOptions = DensifyOptions;
