"use strict";
// automatically generated by the FlatBuffers compiler, do not modify
exports.__esModule = true;
exports.DimensionType = void 0;
var DimensionType;
(function (DimensionType) {
    DimensionType[DimensionType["DENSE"] = 0] = "DENSE";
    DimensionType[DimensionType["SPARSE_CSR"] = 1] = "SPARSE_CSR";
})(DimensionType = exports.DimensionType || (exports.DimensionType = {}));
