"use strict";
// automatically generated by the FlatBuffers compiler, do not modify
exports.__esModule = true;
exports.EqualOptions = void 0;
var flatbuffers = require("flatbuffers");
var EqualOptions = /** @class */ (function () {
    function EqualOptions() {
        this.bb = null;
        this.bb_pos = 0;
    }
    EqualOptions.prototype.__init = function (i, bb) {
        this.bb_pos = i;
        this.bb = bb;
        return this;
    };
    EqualOptions.getRootAsEqualOptions = function (bb, obj) {
        return (obj || new EqualOptions()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
    };
    EqualOptions.getSizePrefixedRootAsEqualOptions = function (bb, obj) {
        bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
        return (obj || new EqualOptions()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
    };
    EqualOptions.startEqualOptions = function (builder) {
        builder.startObject(0);
    };
    EqualOptions.endEqualOptions = function (builder) {
        var offset = builder.endObject();
        return offset;
    };
    EqualOptions.createEqualOptions = function (builder) {
        EqualOptions.startEqualOptions(builder);
        return EqualOptions.endEqualOptions(builder);
    };
    return EqualOptions;
}());
exports.EqualOptions = EqualOptions;
