"use strict";
// automatically generated by the FlatBuffers compiler, do not modify
exports.__esModule = true;
exports.ExpOptions = void 0;
var flatbuffers = require("flatbuffers");
var ExpOptions = /** @class */ (function () {
    function ExpOptions() {
        this.bb = null;
        this.bb_pos = 0;
    }
    ExpOptions.prototype.__init = function (i, bb) {
        this.bb_pos = i;
        this.bb = bb;
        return this;
    };
    ExpOptions.getRootAsExpOptions = function (bb, obj) {
        return (obj || new ExpOptions()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
    };
    ExpOptions.getSizePrefixedRootAsExpOptions = function (bb, obj) {
        bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
        return (obj || new ExpOptions()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
    };
    ExpOptions.startExpOptions = function (builder) {
        builder.startObject(0);
    };
    ExpOptions.endExpOptions = function (builder) {
        var offset = builder.endObject();
        return offset;
    };
    ExpOptions.createExpOptions = function (builder) {
        ExpOptions.startExpOptions(builder);
        return ExpOptions.endExpOptions(builder);
    };
    return ExpOptions;
}());
exports.ExpOptions = ExpOptions;
