"use strict";
// automatically generated by the FlatBuffers compiler, do not modify
exports.__esModule = true;
exports.GatherOptions = void 0;
var flatbuffers = require("flatbuffers");
var GatherOptions = /** @class */ (function () {
    function GatherOptions() {
        this.bb = null;
        this.bb_pos = 0;
    }
    GatherOptions.prototype.__init = function (i, bb) {
        this.bb_pos = i;
        this.bb = bb;
        return this;
    };
    GatherOptions.getRootAsGatherOptions = function (bb, obj) {
        return (obj || new GatherOptions()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
    };
    GatherOptions.getSizePrefixedRootAsGatherOptions = function (bb, obj) {
        bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
        return (obj || new GatherOptions()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
    };
    GatherOptions.prototype.axis = function () {
        var offset = this.bb.__offset(this.bb_pos, 4);
        return offset ? this.bb.readInt32(this.bb_pos + offset) : 0;
    };
    GatherOptions.startGatherOptions = function (builder) {
        builder.startObject(1);
    };
    GatherOptions.addAxis = function (builder, axis) {
        builder.addFieldInt32(0, axis, 0);
    };
    GatherOptions.endGatherOptions = function (builder) {
        var offset = builder.endObject();
        return offset;
    };
    GatherOptions.createGatherOptions = function (builder, axis) {
        GatherOptions.startGatherOptions(builder);
        GatherOptions.addAxis(builder, axis);
        return GatherOptions.endGatherOptions(builder);
    };
    return GatherOptions;
}());
exports.GatherOptions = GatherOptions;
