"use strict";
// automatically generated by the FlatBuffers compiler, do not modify
exports.__esModule = true;
exports.LessOptions = void 0;
var flatbuffers = require("flatbuffers");
var LessOptions = /** @class */ (function () {
    function LessOptions() {
        this.bb = null;
        this.bb_pos = 0;
    }
    LessOptions.prototype.__init = function (i, bb) {
        this.bb_pos = i;
        this.bb = bb;
        return this;
    };
    LessOptions.getRootAsLessOptions = function (bb, obj) {
        return (obj || new LessOptions()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
    };
    LessOptions.getSizePrefixedRootAsLessOptions = function (bb, obj) {
        bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
        return (obj || new LessOptions()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
    };
    LessOptions.startLessOptions = function (builder) {
        builder.startObject(0);
    };
    LessOptions.endLessOptions = function (builder) {
        var offset = builder.endObject();
        return offset;
    };
    LessOptions.createLessOptions = function (builder) {
        LessOptions.startLessOptions(builder);
        return LessOptions.endLessOptions(builder);
    };
    return LessOptions;
}());
exports.LessOptions = LessOptions;
