"use strict";
// automatically generated by the FlatBuffers compiler, do not modify
exports.__esModule = true;
exports.NegOptions = void 0;
var flatbuffers = require("flatbuffers");
var NegOptions = /** @class */ (function () {
    function NegOptions() {
        this.bb = null;
        this.bb_pos = 0;
    }
    NegOptions.prototype.__init = function (i, bb) {
        this.bb_pos = i;
        this.bb = bb;
        return this;
    };
    NegOptions.getRootAsNegOptions = function (bb, obj) {
        return (obj || new NegOptions()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
    };
    NegOptions.getSizePrefixedRootAsNegOptions = function (bb, obj) {
        bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
        return (obj || new NegOptions()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
    };
    NegOptions.startNegOptions = function (builder) {
        builder.startObject(0);
    };
    NegOptions.endNegOptions = function (builder) {
        var offset = builder.endObject();
        return offset;
    };
    NegOptions.createNegOptions = function (builder) {
        NegOptions.startNegOptions(builder);
        return NegOptions.endNegOptions(builder);
    };
    return NegOptions;
}());
exports.NegOptions = NegOptions;
