"use strict";
// automatically generated by the FlatBuffers compiler, do not modify
exports.__esModule = true;
exports.PowOptions = void 0;
var flatbuffers = require("flatbuffers");
var PowOptions = /** @class */ (function () {
    function PowOptions() {
        this.bb = null;
        this.bb_pos = 0;
    }
    PowOptions.prototype.__init = function (i, bb) {
        this.bb_pos = i;
        this.bb = bb;
        return this;
    };
    PowOptions.getRootAsPowOptions = function (bb, obj) {
        return (obj || new PowOptions()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
    };
    PowOptions.getSizePrefixedRootAsPowOptions = function (bb, obj) {
        bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
        return (obj || new PowOptions()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
    };
    PowOptions.startPowOptions = function (builder) {
        builder.startObject(0);
    };
    PowOptions.endPowOptions = function (builder) {
        var offset = builder.endObject();
        return offset;
    };
    PowOptions.createPowOptions = function (builder) {
        PowOptions.startPowOptions(builder);
        return PowOptions.endPowOptions(builder);
    };
    return PowOptions;
}());
exports.PowOptions = PowOptions;
