"use strict";
// automatically generated by the FlatBuffers compiler, do not modify
exports.__esModule = true;
exports.QuantizeOptions = void 0;
var flatbuffers = require("flatbuffers");
var QuantizeOptions = /** @class */ (function () {
    function QuantizeOptions() {
        this.bb = null;
        this.bb_pos = 0;
    }
    QuantizeOptions.prototype.__init = function (i, bb) {
        this.bb_pos = i;
        this.bb = bb;
        return this;
    };
    QuantizeOptions.getRootAsQuantizeOptions = function (bb, obj) {
        return (obj || new QuantizeOptions()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
    };
    QuantizeOptions.getSizePrefixedRootAsQuantizeOptions = function (bb, obj) {
        bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
        return (obj || new QuantizeOptions()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
    };
    QuantizeOptions.startQuantizeOptions = function (builder) {
        builder.startObject(0);
    };
    QuantizeOptions.endQuantizeOptions = function (builder) {
        var offset = builder.endObject();
        return offset;
    };
    QuantizeOptions.createQuantizeOptions = function (builder) {
        QuantizeOptions.startQuantizeOptions(builder);
        return QuantizeOptions.endQuantizeOptions(builder);
    };
    return QuantizeOptions;
}());
exports.QuantizeOptions = QuantizeOptions;
