"use strict";
// automatically generated by the FlatBuffers compiler, do not modify
exports.__esModule = true;
exports.ShapeOptions = void 0;
var flatbuffers = require("flatbuffers");
var tensor_type_1 = require("../circle/tensor-type");
var ShapeOptions = /** @class */ (function () {
    function ShapeOptions() {
        this.bb = null;
        this.bb_pos = 0;
    }
    ShapeOptions.prototype.__init = function (i, bb) {
        this.bb_pos = i;
        this.bb = bb;
        return this;
    };
    ShapeOptions.getRootAsShapeOptions = function (bb, obj) {
        return (obj || new ShapeOptions()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
    };
    ShapeOptions.getSizePrefixedRootAsShapeOptions = function (bb, obj) {
        bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
        return (obj || new ShapeOptions()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
    };
    ShapeOptions.prototype.outType = function () {
        var offset = this.bb.__offset(this.bb_pos, 4);
        return offset ? this.bb.readInt8(this.bb_pos + offset) : tensor_type_1.TensorType.FLOAT32;
    };
    ShapeOptions.startShapeOptions = function (builder) {
        builder.startObject(1);
    };
    ShapeOptions.addOutType = function (builder, outType) {
        builder.addFieldInt8(0, outType, tensor_type_1.TensorType.FLOAT32);
    };
    ShapeOptions.endShapeOptions = function (builder) {
        var offset = builder.endObject();
        return offset;
    };
    ShapeOptions.createShapeOptions = function (builder, outType) {
        ShapeOptions.startShapeOptions(builder);
        ShapeOptions.addOutType(builder, outType);
        return ShapeOptions.endShapeOptions(builder);
    };
    return ShapeOptions;
}());
exports.ShapeOptions = ShapeOptions;
