"use strict";
// automatically generated by the FlatBuffers compiler, do not modify
exports.__esModule = true;
exports.SoftmaxOptions = void 0;
var flatbuffers = require("flatbuffers");
var SoftmaxOptions = /** @class */ (function () {
    function SoftmaxOptions() {
        this.bb = null;
        this.bb_pos = 0;
    }
    SoftmaxOptions.prototype.__init = function (i, bb) {
        this.bb_pos = i;
        this.bb = bb;
        return this;
    };
    SoftmaxOptions.getRootAsSoftmaxOptions = function (bb, obj) {
        return (obj || new SoftmaxOptions()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
    };
    SoftmaxOptions.getSizePrefixedRootAsSoftmaxOptions = function (bb, obj) {
        bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
        return (obj || new SoftmaxOptions()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
    };
    SoftmaxOptions.prototype.beta = function () {
        var offset = this.bb.__offset(this.bb_pos, 4);
        return offset ? this.bb.readFloat32(this.bb_pos + offset) : 0.0;
    };
    SoftmaxOptions.startSoftmaxOptions = function (builder) {
        builder.startObject(1);
    };
    SoftmaxOptions.addBeta = function (builder, beta) {
        builder.addFieldFloat32(0, beta, 0.0);
    };
    SoftmaxOptions.endSoftmaxOptions = function (builder) {
        var offset = builder.endObject();
        return offset;
    };
    SoftmaxOptions.createSoftmaxOptions = function (builder, beta) {
        SoftmaxOptions.startSoftmaxOptions(builder);
        SoftmaxOptions.addBeta(builder, beta);
        return SoftmaxOptions.endSoftmaxOptions(builder);
    };
    return SoftmaxOptions;
}());
exports.SoftmaxOptions = SoftmaxOptions;
