"use strict";
// automatically generated by the FlatBuffers compiler, do not modify
exports.__esModule = true;
exports.TileOptions = void 0;
var flatbuffers = require("flatbuffers");
var TileOptions = /** @class */ (function () {
    function TileOptions() {
        this.bb = null;
        this.bb_pos = 0;
    }
    TileOptions.prototype.__init = function (i, bb) {
        this.bb_pos = i;
        this.bb = bb;
        return this;
    };
    TileOptions.getRootAsTileOptions = function (bb, obj) {
        return (obj || new TileOptions()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
    };
    TileOptions.getSizePrefixedRootAsTileOptions = function (bb, obj) {
        bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
        return (obj || new TileOptions()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
    };
    TileOptions.startTileOptions = function (builder) {
        builder.startObject(0);
    };
    TileOptions.endTileOptions = function (builder) {
        var offset = builder.endObject();
        return offset;
    };
    TileOptions.createTileOptions = function (builder) {
        TileOptions.startTileOptions(builder);
        return TileOptions.endTileOptions(builder);
    };
    return TileOptions;
}());
exports.TileOptions = TileOptions;
