"use strict";
// automatically generated by the FlatBuffers compiler, do not modify
exports.__esModule = true;
exports.TransposeOptions = void 0;
var flatbuffers = require("flatbuffers");
var TransposeOptions = /** @class */ (function () {
    function TransposeOptions() {
        this.bb = null;
        this.bb_pos = 0;
    }
    TransposeOptions.prototype.__init = function (i, bb) {
        this.bb_pos = i;
        this.bb = bb;
        return this;
    };
    TransposeOptions.getRootAsTransposeOptions = function (bb, obj) {
        return (obj || new TransposeOptions()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
    };
    TransposeOptions.getSizePrefixedRootAsTransposeOptions = function (bb, obj) {
        bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
        return (obj || new TransposeOptions()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
    };
    TransposeOptions.startTransposeOptions = function (builder) {
        builder.startObject(0);
    };
    TransposeOptions.endTransposeOptions = function (builder) {
        var offset = builder.endObject();
        return offset;
    };
    TransposeOptions.createTransposeOptions = function (builder) {
        TransposeOptions.startTransposeOptions(builder);
        return TransposeOptions.endTransposeOptions(builder);
    };
    return TransposeOptions;
}());
exports.TransposeOptions = TransposeOptions;
