"use strict";
// automatically generated by the FlatBuffers compiler, do not modify
exports.__esModule = true;
exports.UniqueOptions = void 0;
var flatbuffers = require("flatbuffers");
var tensor_type_1 = require("../circle/tensor-type");
var UniqueOptions = /** @class */ (function () {
    function UniqueOptions() {
        this.bb = null;
        this.bb_pos = 0;
    }
    UniqueOptions.prototype.__init = function (i, bb) {
        this.bb_pos = i;
        this.bb = bb;
        return this;
    };
    UniqueOptions.getRootAsUniqueOptions = function (bb, obj) {
        return (obj || new UniqueOptions()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
    };
    UniqueOptions.getSizePrefixedRootAsUniqueOptions = function (bb, obj) {
        bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
        return (obj || new UniqueOptions()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
    };
    UniqueOptions.prototype.idxOutType = function () {
        var offset = this.bb.__offset(this.bb_pos, 4);
        return offset ? this.bb.readInt8(this.bb_pos + offset) : tensor_type_1.TensorType.INT32;
    };
    UniqueOptions.startUniqueOptions = function (builder) {
        builder.startObject(1);
    };
    UniqueOptions.addIdxOutType = function (builder, idxOutType) {
        builder.addFieldInt8(0, idxOutType, tensor_type_1.TensorType.INT32);
    };
    UniqueOptions.endUniqueOptions = function (builder) {
        var offset = builder.endObject();
        return offset;
    };
    UniqueOptions.createUniqueOptions = function (builder, idxOutType) {
        UniqueOptions.startUniqueOptions(builder);
        UniqueOptions.addIdxOutType(builder, idxOutType);
        return UniqueOptions.endUniqueOptions(builder);
    };
    return UniqueOptions;
}());
exports.UniqueOptions = UniqueOptions;
