"use strict";
// automatically generated by the FlatBuffers compiler, do not modify
exports.__esModule = true;
exports.WhereOptions = void 0;
var flatbuffers = require("flatbuffers");
var WhereOptions = /** @class */ (function () {
    function WhereOptions() {
        this.bb = null;
        this.bb_pos = 0;
    }
    WhereOptions.prototype.__init = function (i, bb) {
        this.bb_pos = i;
        this.bb = bb;
        return this;
    };
    WhereOptions.getRootAsWhereOptions = function (bb, obj) {
        return (obj || new WhereOptions()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
    };
    WhereOptions.getSizePrefixedRootAsWhereOptions = function (bb, obj) {
        bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
        return (obj || new WhereOptions()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
    };
    WhereOptions.startWhereOptions = function (builder) {
        builder.startObject(0);
    };
    WhereOptions.endWhereOptions = function (builder) {
        var offset = builder.endObject();
        return offset;
    };
    WhereOptions.createWhereOptions = function (builder) {
        WhereOptions.startWhereOptions(builder);
        return WhereOptions.endWhereOptions(builder);
    };
    return WhereOptions;
}());
exports.WhereOptions = WhereOptions;
